### ISSUE TITLE
Failure to handle certain archive formats

### ISSUE THREAD

**Issue by nyanshak** [trufflesecurity/trufflehog#1319]
### TruffleHog Version
commit `67972683eaf`

### Expected Behavior

Trufflehog correctly extracts / decompresses, then finds the secret in the archive.

### Actual Behavior

Trufflehog reports `Error unarchiving chunk` and fails to find the secret in the file.

### Steps to Reproduce

Create a folder with secret as test case:
```
ls -la min/
-rw-r--r--  1 user user    2 May  2 11:22 innocuous.txt
-rw-r--r--  1 user user  151 May  2 11:22 secret.txt
```

Make strange archive file (admittedly weird, but I was trying to make this break):

```
zip -r min min
gzip min.zip
mkdir minfail
mv min.zip.gz minfail
```

Run the test:

```
trufflehog filesystem --trace minfail
```

**Comment by nyanshak** [comment]
Added panic to extractor to see more details about the error (even in trace I couldn't see what was going on):

```
panic: input type must be an io.ReaderAt and io.Seeker because of zip format constraints

goroutine 66 [running]:
github.com/trufflesecurity/trufflehog/v3/pkg/handlers.(*Archive).openArchive(0x1b4e2c0?, {0x209e570, 0xc0012c3380}, 0x0, {0x2082500?, 0xc0012c3170?}, 0x166a172?)
	/home/user/src/github.com/trufflesecurity/trufflehog/pkg/handlers/archive.go:98 +0x4cc
github.com/trufflesecurity/trufflehog/v3/pkg/handlers.(*Archive).FromFile.func1()
	/home/user/src/github.com/trufflesecurity/trufflehog/pkg/handlers/archive.go:62 +0x1af
created by github.com/trufflesecurity/trufflehog/v3/pkg/handlers.(*Archive).FromFile
	/home/user/src/github.com/trufflesecurity/trufflehog/pkg/handlers/archive.go:57 +0xf5
```
