### ISSUE TITLE
PermissionError: [WinError 5] Access is denied:

### ISSUE THREAD

**Issue by sagar1351** [trufflesecurity/trufflehog#153]
I was using truffleHog module in nodeJs. .
If i am trying to do using cli commands it gives correct result.

But By using python shell I got below issue 
I am attaching console snapshot with errors.

Error: PermissionError: [WinError 5] Access is denied: 'C:\\Users\\sagar\\AppData\\Local\\Temp\\tmp6ji867wv'
    at PythonShell.parseError (E:\node_server\node_modules\python-shell\index.js:246:21)
    at terminateIfNeeded (E:\node_server\node_modules\python-shell\index.js:129:32)
    at ChildProcess.<anonymous> (E:\node_server\node_modules\python-shell\index.js:121:13)
    at ChildProcess.emit (events.js:189:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
    ----- Python Traceback -----
    File "C:\Users\sagar\AppData\Local\Programs\Python\Python38-32\lib\shutil.py", line 567, in _rmtree_unsafe
      os.rmdir(path)
  PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\sagar\\AppData\\Local\\Temp\\tmp6ji867wv'

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "truffleHog.py", line 312, in <module>
      main()
    File "truffleHog.py", line 57, in main
      output = find_strings(args.git_url, args.since_commit, args.max_depth, args.output_json, args.do_regex, do_entropy, surpress_output=False, branch=args.branch, repo_path=args.repo_path)
    File "truffleHog.py", line 303, in find_strings
      shutil.rmtree(project_path, onerror=del_rw)
    File "C:\Users\sagar\AppData\Local\Programs\Python\Python38-32\lib\shutil.py", line 681, in rmtree
      return _rmtree_unsafe(path, onerror)
    File "C:\Users\sagar\AppData\Local\Programs\Python\Python38-32\lib\shutil.py", line 569, in _rmtree_unsafe
      onerror(os.rmdir, path, sys.exc_info())
    File "truffleHog.py", line 83, in del_rw
      os.remove(name)

Please suggest.

**Comment by klickyfan** [comment]
Do you ever figure this out? I am having same problem.

**Comment by sagar1351** [comment]
@klickyfan Yes I resolved this issue can you please message me your requirement on my email:-sagar.1351@gmail.com

**Comment by pendraggon87** [comment]
What was the resolution?

**Comment by Exterminat0r** [comment]
I am also experiencing the same issue. Any tips?

**Comment by fuzboxz** [comment]
Same here.

**Comment by jveldhuijzen** [comment]
It's the same issue as posted here in this pr: #203 
What I did locally was pipe the output of the command into a a file (this error only pops up at he end of the process)
`trufflehog --json <path or online git repo you want to scan>  > output.json`

**Comment by dustin-decker** [comment]
Hey there, we've just released the next major version of TruffleHog! 

It is a complete rewrite that scans more data sources and now supports detecting and verifying over 600 credentials.
Please check it out when you can.

https://trufflesecurity.com/blog/introducing-trufflehog-v3

We're no longer maintaining v2 so I am closing this issue.
