### ISSUE TITLE
[Bug] Can't scan a single local file in a git repository

### ISSUE THREAD

**Issue by MVrachev** [trufflesecurity/trufflehog#162]
Hi, when I scan my local repository with this command:
```
trufflehog -x=truffLogConfig.txt --max_depth=1 file:///Users/mvrachev/Martins/go/src/github.com/precaution/
```

it works flawlessly.

Then I want to scan only index.js file. I am sure that the `index.js` file is committed and I run 
`truffleHog` with this command:

```
trufflehog -x=truffLogConfig.txt --max_depth=1 file:///Users/mvrachev/Martins/go/src/github.com/precaution/index.js
```

and I get this traceback:

```
Traceback (most recent call last):
  File "/usr/local/bin/trufflehog", line 11, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/truffleHog/truffleHog.py", line 82, in main
    surpress_output=False, branch=args.branch, repo_path=args.repo_path, path_inclusions=path_inclusions, path_exclusions=path_exclusions)
  File "/Library/Python/2.7/site-packages/truffleHog/truffleHog.py", line 309, in find_strings
    project_path = clone_git_repo(git_url)
  File "/Library/Python/2.7/site-packages/truffleHog/truffleHog.py", line 152, in clone_git_repo
    Repo.clone_from(git_url, project_path)
  File "/Library/Python/2.7/site-packages/git/repo/base.py", line 925, in clone_from
    return cls._clone(git, url, to_path, GitCmdObjectDB, progress, **kwargs)
  File "/Library/Python/2.7/site-packages/git/repo/base.py", line 880, in _clone
    finalize_process(proc, stderr=stderr)
  File "/Library/Python/2.7/site-packages/git/util.py", line 341, in finalize_process
    proc.wait(**kwargs)
  File "/Library/Python/2.7/site-packages/git/cmd.py", line 291, in wait
    raise GitCommandError(self.args, status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v file:///Users/mvrachev/Martins/go/src/github.com/precaution/index.js /var/folders/jl/y5y8nlms7tj7xryb_qqyybpr0000gq/T/tmp72zqvi
  stderr: 'Cloning into '/var/folders/jl/y5y8nlms7tj7xryb_qqyybpr0000gq/T/tmp72zqvi'...
fatal: invalid gitfile format: /Users/mvrachev/Martins/go/src/github.com/precaution/index.js
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I tried running this command instead 
``` 
trufflehog -x=truffLogConfig.txt --max_depth=1 file://Users/mvrachev/Martins/go/src/github.com/precaution/index.js
```

and again I get the same error.

**Comment by dustin-decker** [comment]
Hey there, we've just released the next major version of TruffleHog! 

We have added filesystem scanning support, but file and stdin scanning is on the way too.

It is a complete rewrite that scans more data sources and now supports detecting and verifying over 600 credentials.
Please check it out when you can.

https://trufflesecurity.com/blog/introducing-trufflehog-v3

We're no longer maintaining v2 so I am closing this issue.

**Comment by TheTechromancer** [comment]
@dustin-decker any word on stdin scanning? We are in need of this feature for Trufflehog's integration with [BBOT](https://github.com/blacklanternsecurity/bbot).
