### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by shivankar-madaan** [trufflesecurity/trufflehog#197]
Hi
Got UnicodeEncodeError for a couple of times now
```
Traceback (most recent call last):
  File "/usr/local/bin/trufflehog", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/truffleHog/truffleHog.py", line 82, in main
    surpress_output=False, branch=args.branch, repo_path=args.repo_path, path_inclusions=path_inclusions, path_exclusions=path_exclusions)
  File "/usr/local/lib/python3.6/dist-packages/truffleHog/truffleHog.py", line 344, in find_strings
    foundIssues = diff_worker(diff, curr_commit, prev_commit, branch_name, commitHash, custom_regexes, do_entropy, do_regex, printJson, surpress_output, path_inclusions, path_exclusions)
  File "/usr/local/lib/python3.6/dist-packages/truffleHog/truffleHog.py", line 265, in diff_worker
    print_results(printJson, foundIssue)
  File "/usr/local/lib/python3.6/dist-packages/truffleHog/truffleHog.py", line 182, in print_results
    print(printableDiff)
UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 151: ordinal not in range(128)
```

and 

```
Traceback (most recent call last):
  File "/usr/local/bin/trufflehog", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/truffleHog/truffleHog.py", line 82, in main
    surpress_output=False, branch=args.branch, repo_path=args.repo_path, path_inclusions=path_inclusions, path_exclusions=path_exclusions)
  File "/usr/local/lib/python3.6/dist-packages/truffleHog/truffleHog.py", line 344, in find_strings
    foundIssues = diff_worker(diff, curr_commit, prev_commit, branch_name, commitHash, custom_regexes, do_entropy, do_regex, printJson, surpress_output, path_inclusions, path_exclusions)
  File "/usr/local/lib/python3.6/dist-packages/truffleHog/truffleHog.py", line 265, in diff_worker
    print_results(printJson, foundIssue)
  File "/usr/local/lib/python3.6/dist-packages/truffleHog/truffleHog.py", line 182, in print_results
    print(printableDiff)
UnicodeEncodeError: 'ascii' codec can't encode character '\ufeff' in position 17: ordinal not in range(128)
```

I have installed trufflehog, via pip3

**Comment by dustin-decker** [comment]
Hey there, we've just released the next major version of TruffleHog! 

It is a complete rewrite that scans more data sources and now supports detecting and verifying over 600 credentials.
Please check it out when you can.

https://trufflesecurity.com/blog/introducing-trufflehog-v3

We're no longer maintaining v2 so I am closing this issue.
