### ISSUE TITLE
.7z archive: `panic: runtime error: index out of range [18155] with length 328`

### ISSUE THREAD

**Issue by rgmz** [trufflesecurity/trufflehog#2036]
Please review the [Community Note](https://github.com/trufflesecurity/trufflehog/blob/main/.github/community_note.md) before submitting

### TruffleHog Version

The latest version built locally.

### Trace Output

```
🐷🔑🐷  TruffleHog. Unearth your secrets. 🐷🔑🐷

2023-10-29T09:58:39-04:00       info-0  trufflehog      handling binary file    {"job_id": 1, "source_manager_worker_id": "HhBjw", "source_type": "SOURCE_TYPE_GIT", "source_name": "trufflehog - git", "path": "ubuntu-archive-keyring.gpg", "repo": "https://github.com/ValveSoftware/steam-runtime.git", "commit": "2cb0efbbcb88818818e42e2b7bb654f69103ddb3"}
2023-10-29T09:58:39-04:00       info-0  trufflehog      handling binary file    {"job_id": 1, "source_manager_worker_id": "HhBjw", "source_type": "SOURCE_TYPE_GIT", "source_name": "trufflehog - git", "path": "packages/source/libsdl2/libsdl2_2.0.3.tar.gz", "repo": "https://github.com/ValveSoftware/steam-runtime.git", "commit": "35b3f126adfc7acbc6292616237f2ec678a626cf"}
2023-10-29T09:58:39-04:00       info-0  trufflehog      handling binary file    {"job_id": 1, "source_manager_worker_id": "HhBjw", "source_type": "SOURCE_TYPE_GIT", "source_name": "trufflehog - git", "path": "crosstool/ct-ng-win/x86_64-4.8.2-release-win32-sjlj-rt_v3-rev2.7z", "repo": "https://github.com/ValveSoftware/steam-runtime.git", "commit": "9e69aaf3b3a773626242beea9897e7bb85441d43"}
panic: runtime error: index out of range [18155] with length 328

goroutine 8504 [running]:
github.com/bodgit/sevenzip.readFilesInfo({0x7fdd20343390?, 0xc0016140c0})
        /home/user/go/pkg/mod/github.com/bodgit/sevenzip@v1.3.0/types.go:707 +0x650
github.com/bodgit/sevenzip.readHeader({0x7fdd20343390, 0xc0016140c0})
        /home/user/go/pkg/mod/github.com/bodgit/sevenzip@v1.3.0/types.go:811 +0xdc
github.com/bodgit/sevenzip.readEncodedHeader({0x7fdd20343390, 0xc0016140c0})
        /home/user/go/pkg/mod/github.com/bodgit/sevenzip@v1.3.0/types.go:849 +0x9a
github.com/bodgit/sevenzip.(*Reader).init(0xc000b72a20, {0x7fdd20343138?, 0xc0042260c0}, 0x38477bc)
        /home/user/go/pkg/mod/github.com/bodgit/sevenzip@v1.3.0/reader.go:356 +0x867
github.com/bodgit/sevenzip.NewReaderWithPassword({0x7fdd20343138, 0xc0042260c0}, 0x38477bc, {0x0, 0x0})
        /home/user/go/pkg/mod/github.com/bodgit/sevenzip@v1.3.0/reader.go:242 +0x93
github.com/mholt/archiver/v4.SevenZip.Extract({0x0?, {0x0?, 0x0?}}, {0x3bfdc68, 0xc004226660}, {0x3bcc340?, 0xc0042260c0?}, {0x0, 0x0, 0x0}, ...)
        /home/user/go/pkg/mod/github.com/mholt/archiver/v4@v4.0.0-alpha.8/7z.go:76 +0x12b
github.com/trufflesecurity/trufflehog/v3/pkg/handlers.(*Archive).openArchive(0xc000116240, {0x3bfdd10, 0xc0012fa000}, 0x0, {0x3bcc340, 0xc0042260c0}, 0xc00e4560c0)
        /home/user/dev/github.com/trufflesecurity/trufflehog/pkg/handlers/archive.go:114 +0x2b3
github.com/trufflesecurity/trufflehog/v3/pkg/handlers.(*Archive).FromFile.func1()
        /home/user/dev/github.com/trufflesecurity/trufflehog/pkg/handlers/archive.go:76 +0x1af
created by github.com/trufflesecurity/trufflehog/v3/pkg/handlers.(*Archive).FromFile in goroutine 151
        /home/user/dev/github.com/trufflesecurity/trufflehog/pkg/handlers/archive.go:71 +0xe5
```

### Expected Behavior

The archive is decoded successfully.

### Actual Behavior

A runtime error is thrown.

### Steps to Reproduce

Attempt to scan: https://github.com/ValveSoftware/steam-runtime

The problematic file appears to be: https://github.com/ValveSoftware/steam-runtime/blob/9e69aaf3b3a773626242beea9897e7bb8544/crosstool/ct-ng-win/x86_64-4.8.2-release-win32-sjlj-rt_v3-rev2.7z

## Environment
N/A

## Additional Context

This is likely a bug with https://github.com/bodgit/sevenzip. I will cross-post this there soon.

### References

N/A

**Comment by rgmz** [comment]
This bug was fixed in [`github.com/bodgit/sevenzip@v1.4.2`](https://github.com/bodgit/sevenzip/releases/tag/v1.4.2).
