### ISSUE TITLE
Nil map in AWS Session Key detector

### ISSUE THREAD

**Issue by rgmz** [trufflesecurity/trufflehog#2116]
Please review the [Community Note](https://github.com/trufflesecurity/trufflehog/blob/main/.github/community_note.md) before submitting

### TruffleHog Version

```
2023-11-20T01:26:01-05:00       error   trufflehog      goroutine 233 [running]:
runtime/debug.Stack()
        /home/user/sdk/go1.21.0/src/runtime/debug/stack.go:24 +0x5e
github.com/trufflesecurity/trufflehog/v3/pkg/common.Recover({0x3c2be40, 0xc146c7eba0})
        /home/user/dev/github.com/trufflesecurity/trufflehog/pkg/common/recover.go:17 +0x58
panic({0x2e79e40?, 0x3bebda0?})
        /home/user/sdk/go1.21.0/src/runtime/panic.go:914 +0x21f
github.com/trufflesecurity/trufflehog/v3/pkg/detectors/awssessionkeys.scanner.FromData({0x0?, 0xc002c8c150?}, {0x7f865c4a93b8, 0xc146c7eba0}, 0x1, {0xc125760000?, 0x31c4d20?, 0x0?})
        /home/user/dev/github.com/trufflesecurity/trufflehog/pkg/detectors/awssessionkeys/awssessionkey.go:157 +0xac6
github.com/trufflesecurity/trufflehog/v3/pkg/engine.(*Engine).detectChunk(0xc000e282c0, {0x3c2be40?, 0xc0009c7d70?}, {{0x3c148e0, 0xc001810f50}, {{0x33e7e8b, 0x13}, 0x1, 0x1, 0x7, ...}, ...})
        /home/user/dev/github.com/trufflesecurity/trufflehog/pkg/engine/engine.go:508 +0x172
github.com/trufflesecurity/trufflehog/v3/pkg/engine.(*Engine).detectChunks(...)
        /home/user/dev/github.com/trufflesecurity/trufflehog/pkg/engine/engine.go:495
github.com/trufflesecurity/trufflehog/v3/pkg/engine.(*Engine).startWorkers.func2()
        /home/user/dev/github.com/trufflesecurity/trufflehog/pkg/engine/engine.go:390 +0x1f5
created by github.com/trufflesecurity/trufflehog/v3/pkg/engine.(*Engine).startWorkers in goroutine 1
        /home/user/dev/github.com/trufflesecurity/trufflehog/pkg/engine/engine.go:386 +0x276
        {"detector_worker_id": "2SsRt", "timeout": 10, "recover": "assignment to entry in nil map", "error": "panic"}
2023-11-20T01:26:01-05:00       info-0  trufflehog      sentry flush failed     {"detector_worker_id": "2SsRt", "timeout": 10}
```

Culprit:
https://github.com/trufflesecurity/trufflehog/blob/39a603d2dc5d8c011e8ad54bffb9e12fb18fe2b4/pkg/detectors/awssessionkeys/awssessionkey.go#L153-L159

**Comment by cerontrustly** [comment]
Same here...

**Comment by gabrielssant0s** [comment]
Same error here.
