### ISSUE TITLE
Exception raised with repo in Windows 10 v21H1

### ISSUE THREAD

**Issue by BitCruncher0** [trufflesecurity/trufflehog#272]
```
trufflehog file:///path/to/project/
```
```
Traceback (most recent call last):
  File "C:\Users\boden\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 615, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\boden\\AppData\\Local\\Temp\\tmpgsfhddld\\.git\\objects\\pack\\pack-9c70bb09232a0ffb61a7a848afaf1bd384bd322b.idx'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\boden\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\boden\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\boden\AppData\Local\Programs\Python\Python310\Scripts\trufflehog.exe\__main__.py", line 7, in <module>
  File "C:\Users\boden\AppData\Local\Programs\Python\Python310\lib\site-packages\truffleHog\truffleHog.py", line 92, in main
    output = find_strings(args.git_url, args.since_commit, args.max_depth, args.output_json, args.do_regex, do_entropy,
  File "C:\Users\boden\AppData\Local\Programs\Python\Python310\lib\site-packages\truffleHog\truffleHog.py", line 381, in find_strings
    shutil.rmtree(project_path, onerror=del_rw)
  File "C:\Users\boden\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 739, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\boden\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 612, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Users\boden\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 612, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Users\boden\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 612, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Users\boden\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 617, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Users\boden\AppData\Local\Programs\Python\Python310\lib\site-packages\truffleHog\truffleHog.py", line 125, in del_rw
    os.remove(name)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\boden\\AppData\\Local\\Temp\\tmpgsfhddld\\.git\\objects\\pack\\pack-9c70bb09232a0ffb61a7a848afaf1bd384bd322b.idx'
```

* Windows 10
* Version 21H1

**Comment by dustin-decker** [comment]
Hey there, we've just released the next major version of TruffleHog! 

It is a complete rewrite that scans more data sources and now supports detecting and verifying over 600 credentials.
Please check it out when you can.

https://trufflesecurity.com/blog/introducing-trufflehog-v3

We're no longer maintaining v2 so I am closing this issue.
