### ISSUE TITLE
"filesystem" command segfaults on bad symlinks

### ISSUE THREAD

**Issue by acut3** [trufflesecurity/trufflehog#298]
**Describe the bug**
`trufflehog filesystem` segfaults when the target directory contains a symlink to a non-existing file.

**To Reproduce**
```sh
newdir=$(mktemp -d -p .)
ln -s non_existing_target $newdir/link
trufflehog filesystem --directory=$newdir
```
Will result in:
```
WARN[0000] unable to stat file: tmp.hl0jZSoenB/link      error="stat tmp.hl0jZSoenB/link: no such file or directory"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x11f4382]
```

**Expected behavior**
Invalid links should be skipped, maybe with a warning.

**Output**
```
$ newdir=$(mktemp -d -p .); ln -s non_existing_target $newdir/link; trufflehog --debug filesystem --directory=$newdir
DEBU[0000] running version 3.0.3                        
2022/04/06 13:50:03 [updater parent] run
2022/04/06 13:50:03 [updater parent] checking for updates...
2022/04/06 13:50:03 [updater parent] failed to get latest version: already up to date
2022/04/06 13:50:03 [updater parent] starting /home/nicolas/go/bin/trufflehog
DEBU[0000] running version 3.0.3                        
2022/04/06 13:50:03 [updater child#1] run
2022/04/06 13:50:03 [updater child#1] start program
trufflehog 3.0.3
DEBU[0000] running with up to 32 workers                
DEBU[0000] loaded 1 decoders                            
DEBU[0000] loaded 610 detectors total, 610 with verification enabled. 0 with verification disabled 
INFO[0000] starting pprof and fgprof server on :18066 /debug/pprof and /debug/fgprof 
🐷🔑🐷  TruffleHog. Unearth your secrets. 🐷🔑🐷

WARN[0000] unable to stat file: tmp.rYZ4OL9fWE/link      error="stat tmp.rYZ4OL9fWE/link: no such file or directory"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x11f4382]

goroutine 97 [running]:
github.com/trufflesecurity/trufflehog/v3/pkg/sources/filesystem.(*Source).Chunks.func2({0xc000b88098, 0x4}, {0xc001103d78, 0x4d3078}, {0x0, 0x0})
        /home/runner/work/trufflehog/trufflehog/pkg/sources/filesystem/filesystem.go:103 +0x1a2
io/fs.walkDir({0x1d88660, 0xc00129c030}, {0xc000b88098, 0x4}, {0x1db5cf0, 0xc0002a8080}, 0xc0005f9f50)
        /opt/hostedtoolcache/go/1.17.8/x64/src/io/fs/walk.go:66 +0x83
io/fs.walkDir({0x1d88660, 0xc00129c030}, {0x1a4801d, 0x1}, {0x1db5c10, 0xc00129c040}, 0xc0005f9f50)
        /opt/hostedtoolcache/go/1.17.8/x64/src/io/fs/walk.go:85 +0x27f
io/fs.WalkDir({0x1d88660, 0xc00129c030}, {0x1a4801d, 0x1}, 0xc001103f50)
        /opt/hostedtoolcache/go/1.17.8/x64/src/io/fs/walk.go:112 +0xde
github.com/trufflesecurity/trufflehog/v3/pkg/sources/filesystem.(*Source).Chunks(0xc000f6a1b0, {0x1db52e0, 0xc000050120}, 0xc0000539e0)
        /home/runner/work/trufflehog/trufflehog/pkg/sources/filesystem/filesystem.go:92 +0x27d
github.com/trufflesecurity/trufflehog/v3/pkg/engine.(*Engine).ScanFileSystem.func1()
        /home/runner/work/trufflehog/trufflehog/pkg/engine/filesystem.go:31 +0x36
created by github.com/trufflesecurity/trufflehog/v3/pkg/engine.(*Engine).ScanFileSystem
        /home/runner/work/trufflehog/trufflehog/pkg/engine/filesystem.go:30 +0x2a5
2022/04/06 13:50:03 [updater parent] prog exited with 2
```

**Desktop (please complete the following information):**
 - OS: arch linux
 - go version go1.18 linux/amd64
 - trufflehog built from source, commit 33aa6f9cab7f13cafd422f5652b725fdaed91104

**Comment by dustin-decker** [comment]
Fixed by v3.0.4 (building now) in #299
