### ISSUE TITLE
panic: runtime error: slice bounds out of range [47:42]

### ISSUE THREAD

**Issue by McPatate** [trufflesecurity/trufflehog#3314]
### TruffleHog Version

```
# trufflehog --version
trufflehog 3.82.2
```

### Trace Output

```json
{"level":"error","ts":"2024-09-23T15:22:10+02:00","logger":"trufflehog","msg":"goroutine 123 [running]:\nruntime/debug.Stack()\n\t/opt/hostedtoolcache/go/1.22.7/x64/src/runtime/debug/stack.go:24 +0x64\ngithub.com/trufflesecurity/trufflehog/v3/pkg/common.Recover({0x10925f1a0, 0x140015e48a0})\n\t/home/runner/work/trufflehog/trufflehog/pkg/common/recover.go:17 +0x44\npanic({0x108f8a2a0?, 0x1400255c9f0?})\n\t/opt/hostedtoolcache/go/1.22.7/x64/src/runtime/panic.go:770 +0x124\ngithub.com/trufflesecurity/trufflehog/v3/pkg/detectors/openai.Scanner.FromData({0x10925f1a0?}, {0x113879c10, 0x14008f83620}, 0x0, {0x14001ef41d5?, 0x0?, 0x0?})\n\t/home/runner/work/trufflehog/trufflehog/pkg/detectors/openai/openai.go:52 +0x3e0\ngithub.com/trufflesecurity/trufflehog/v3/pkg/engine.(*Engine).verificationOverlapWorker(0x14000f4c000, {0x10925f1a0, 0x140015e48a0})\n\t/home/runner/work/trufflehog/trufflehog/pkg/engine/engine.go:923 +0x3fc\ngithub.com/trufflesecurity/trufflehog/v3/pkg/engine.(*Engine).startVerificationOverlapWorkers.func1()\n\t/home/runner/work/trufflehog/trufflehog/pkg/engine/engine.go:683 +0xe4\ncreated by github.com/trufflesecurity/trufflehog/v3/pkg/engine.(*Engine).startVerificationOverlapWorkers in goroutine 1\n\t/home/runner/work/trufflehog/trufflehog/pkg/engine/engine.go:679 +0x100\n","verification_overlap_worker_id":"9z5eV","recover":"runtime error: slice bounds out of range [47:42]","error":"panic"}
```

### Expected Behavior

Exit on error

### Actual Behavior

Hangs indefinitely

### Steps to Reproduce

You can run `trufflehog filesystem` on the following file: [02-09-2024 20-02/spaces_df.csv](https://huggingface.co/datasets/Weyaxi/huggingface-leaderboard/blob/4d979c0921c19a660124d43708fe74496e55e80a/02-09-2024%2020-02/spaces_df.csv)

This will output the aforementioned error.

## Environment
 * OS: MacOS, but also appears on amzn linux

**Comment by zricethezav** [comment]
https://github.com/trufflesecurity/trufflehog/blob/97fd2f80ee22e46056da979b7a15634c0e8701ff/pkg/detectors/openai/openai.go#L52 error coming from here

**Comment by rgmz** [comment]
Prior to #3167, the pattern had a fixed or minimum length. IMO the new pattern seems problematic because quite a few invalid things can match it. (e.g., `sk-aT3BlbkFJb`).
```regex
sk-[[:alnum:]_-]+T3BlbkFJ[[:alnum:]_-]+
```

**Comment by zricethezav** [comment]
@McPatate should be fixed w/ https://github.com/trufflesecurity/trufflehog/pull/3316

**Comment by McPatate** [comment]
Thanks for the quick fix!

**Comment by McPatate** [comment]
Coming back to this real quick, trufflehog hangs indefinitely after the panic occurs. Shouldn't it exit itself when it cannot continue making progress?

**Comment by zricethezav** [comment]
@McPatate you're absolutely correct. Hanging indefinitely is clearly a bug that needs to be fixed and deserves its own issue. @ahrav might be able to provide some more context on why it is hanging indefinitely.

Did the PR merged in yesterday help resolve your specific issue?

**Comment by McPatate** [comment]
> Did the PR merged in yesterday help resolve your specific issue?

I've circumvented the issue by parsing stderr logs and killing the subprocess when `error` is set to `panic`. Was waiting for a release to try it out, but I can setup trufflehog locally to test if there's value in doing so for you.

**Comment by zricethezav** [comment]
Looks like Ahrav just cut a release a few minutes ago: https://github.com/trufflesecurity/trufflehog/releases/tag/v3.82.3

**Comment by McPatate** [comment]
Just tested it out, it works on the file I mentioned.

**Comment by ahrav** [comment]
> @McPatate you're absolutely correct. Hanging indefinitely is clearly a bug that needs to be fixed and deserves its own issue. @ahrav might be able to provide some more context on why it is hanging indefinitely.
> 
> Did the PR merged in yesterday help resolve your specific issue?

I'm glad the underlying issue was resolved. However, I can explain why the scanner appeared hung. If the scanning engine encounters a panic, we have recovery code that prevents the scanner from crashing. Unfortunately, once we recover, the goroutine that triggered the panic can't be reused. After multiple panics, all worker goroutines can be reduced to zero, which makes the application seem hung since there are no workers left to process the chunks.

We're working on designs to improve resilience, including a mechanism to restart worker goroutines after a panic. Ideally, though, we should aim to avoid panics altogether. Sorry for the inconvenience, but I’m glad Zach resolved the root cause.
