### ISSUE TITLE
GitHub analyzer panic

### ISSUE THREAD

**Issue by rgmz** [trufflesecurity/trufflehog#3697]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1009e5f34]

goroutine 1 [running]:
github.com/trufflesecurity/trufflehog/v3/pkg/analyzer/analyzers/github/common.PrintGists({0x14001714b40, 0x24, 0x140054fd6a8?}, 0x0)
        /home/g/thog/pkg/analyzer/analyzers/github/common/github.go:177 +0x484
github.com/trufflesecurity/trufflehog/v3/pkg/analyzer/analyzers/github/finegrained.PrintFineGrainedToken(0x1400078c360, 0x140010df6c0)
        /home/g/thog/pkg/analyzer/analyzers/github/finegrained/finegrained.go:1333 +0x160
github.com/trufflesecurity/trufflehog/v3/pkg/analyzer/analyzers/github.AnalyzeAndPrintPermissions(0x1400078c360, {0x14001795080?, 0x1036cb9f8?})
        /home/g/thog/pkg/analyzer/analyzers/github/github.go:165 +0x1dc
github.com/trufflesecurity/trufflehog/v3/pkg/analyzer.Run({0x1036d6c49?, 0x7?})
        /home/g/thog/pkg/analyzer/cli.go:66 +0x218
main.run({0x1, {0x1400007e110, 0x28}, {0xc1caa5132f3cf0f8, 0x1b79a696, 0x1077fe940}, {0x0, 0x0}, {0x1078387a0, 0x0, ...}, ...})
        /home/g/thog/main.go:493 +0xbf8
github.com/jpillora/overseer.(*child).run(0x140027dbb20)
        /home/g/go/pkg/mod/github.com/trufflesecurity/overseer@v1.2.8/proc_child.go:77 +0x278
github.com/jpillora/overseer.runErr(0x1400120f180)
        /home/g/go/pkg/mod/github.com/trufflesecurity/overseer@v1.2.8/overseer.go:164 +0x128
github.com/jpillora/overseer.RunErr(...)
        /home/g/go/pkg/mod/github.com/trufflesecurity/overseer@v1.2.8/overseer.go:94
main.main()
        /home/g/thog/main.go:326 +0x34c
```

**Comment by amanfcp** [comment]
Hi @rgmz,

Based on the stack trace, it looks like the issue is occurring when attempting to print the Gists list. I tested this on my end by creating several Gists (including ones with empty fields like the description), and the analyzer ran without any errors, as shown in the snapshot below.

Could you please try reproducing the issue using the latest code? If the problem still occurs, we can take a closer look and investigate further.

![Image](https://github.com/user-attachments/assets/562be16e-6d8b-4b43-b070-526e52d2594d)

**Comment by amanfcp** [comment]
The error suggests that we only need to add `nil` check on `gist` since it's coming in slice of pointer -> `gists []*gh.Gist`. 
If any value (e.g. `*gist.ID`) is nil, it will simply print _nil_.

**Comment by rgmz** [comment]
> If any value (e.g. `*gist.ID`) is nil, it will simply print _nil_.

This isn't how `nil` and pointer dereferencing works in Go.

https://go.dev/play/p/IpXwnA6bCt_A
