### ISSUE TITLE
Installation problem. 

### ISSUE THREAD

**Issue by poon64** [trufflesecurity/trufflehog#57]
I'm trying to install truffleHog in my RHEL 7.4 installation. 
But everytime I try to install I get the problem below, python and pip version at the end. 
Any idea wht's causing this? 

-bash-4.2$ pip install truffleHog
Collecting truffleHog
Collecting GitPython==2.1.1 (from truffleHog)
  Using cached GitPython-2.1.1-py2.py3-none-any.whl
Collecting gitdb2>=2.0.0 (from GitPython==2.1.1->truffleHog)
  Using cached gitdb2-2.0.2-py2.py3-none-any.whl
Collecting smmap2>=2.0.0 (from gitdb2>=2.0.0->GitPython==2.1.1->truffleHog)
  Using cached smmap2-2.0.3-py2.py3-none-any.whl
Installing collected packages: smmap2, gitdb2, GitPython, truffleHog
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/lib/python2.7/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/lib/python2.7/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/usr/lib/python2.7/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/lib/python2.7/site-packages/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/usr/lib/python2.7/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/usr/lib64/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/lib/python2.7/site-packages/smmap'

-bash-4.2$ python --version
Python 2.7.5
-bash-4.2$ pip --version 
pip 9.0.1 from /usr/lib/python2.7/site-packages (python 2.7)
-bash-4.2$

**Comment by cjbarker** [comment]
Would appear you don't have file permissions.  You have three options.

1) change file permissions: sudo chown -R /usr/lib/python2.7/site-packages/smmap
2) install via root: sudo pip install truffleHog
3) install via local user scheme: pip install --user truffleHog

**Comment by poon64** [comment]
I guess that you mean chmod in stead of chown :) 
But the file smmap doesn't exist in the system. 
When I tried to install again I got other problems now, 

-bash-4.2$ git remote -v
origin	https://github.com/dxa4481/truffleHog.git (fetch)
origin	https://github.com/dxa4481/truffleHog.git (push)
-bash-4.2$ git pull
Already up-to-date.
-bash-4.2$ pip install truffleHog
Collecting truffleHog
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/site-packages/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python2.7/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python2.7/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/site-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/usr/lib/python2.7/site-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python2.7/site-packages/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/usr/lib/python2.7/site-packages/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/usr/lib/python2.7/site-packages/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/usr/lib/python2.7/site-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/usr/lib/python2.7/site-packages/pip/index.py", line 792, in get_page
    "Cache-Control": "max-age=600",
  File "/usr/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/site-packages/pip/download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/pip/_vendor/cachecontrol/adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/usr/lib/python2.7/site-packages/pip/_vendor/requests/adapters.py", line 390, in send
    conn = self.get_connection(request.url, proxies)
  File "/usr/lib/python2.7/site-packages/pip/_vendor/requests/adapters.py", line 290, in get_connection
    proxy_manager = self.proxy_manager_for(proxy)
  File "/usr/lib/python2.7/site-packages/pip/_vendor/requests/adapters.py", line 184, in proxy_manager_for
    **proxy_kwargs
  File "/usr/lib/python2.7/site-packages/pip/_vendor/requests/adapters.py", line 43, in SOCKSProxyManager
    raise InvalidSchema("Missing dependencies for SOCKS support.")
InvalidSchema: Missing dependencies for SOCKS support.

**Comment by rupsray** [comment]
@poon64 Follow https://dzone.com/articles/cloud-security-best-practices-finding-securing-and for installing truffleHog. Even I was facing the same issue. This solved my issues.

**Comment by outkaj** [comment]
Following the instructions from the link above gives me the following error:

```
Traceback (most recent call last):
  File "truffleHog.py", line 19, in <module>
    from truffleHogRegexes.regexChecks import regexes
ModuleNotFoundError: No module named 'truffleHogRegexes'
```

**Comment by AlexanderGerasymenko** [comment]
same as for @outkaj

**Comment by dustin-decker** [comment]
Hey there, we've just released the next major version of TruffleHog! 

It is a complete rewrite that scans more data sources and now supports detecting and verifying over 600 credentials.
Please check it out when you can.

https://trufflesecurity.com/blog/introducing-trufflehog-v3

We're no longer maintaining v2 so I am closing this issue.

**Comment by Abdallanasser819** [comment]
> @poon64 would appear you don't have file permissions. You have three options.
> 
>     1. change file permissions: sudo chown -R /usr/lib/python2.7/site-packages/smmap
> 
>     2. install via root: sudo pip install truffleHog
> 
>     3. install via local user scheme: pip install --user truffleHog

num 2 worked.. thak you very much
